// config/constants.js

/**
 * @file Centraliza las constantes de la aplicación para evitar "magic strings".
 * @module config/constants
 */

const ROLES = Object.freeze({
    OWNER: 'owner',
    ADMIN: 'administrador',
    MODERATOR: 'moderador',
    USER: 'usuario'
});

const PRODUCT_STATUS = Object.freeze({
    ACTIVE: 'Activa',
    NOTICE: 'Aviso de Vencimiento',
    EXPIRED: 'Vencida',
    RENEWED: 'Renovada',
    CANCELED: 'Cancelada',
    TRIAL: 'Prueba'
});

const FLOW_STEPS = Object.freeze({
    // Pasos Flujo de Añadir Cliente
    AWAIT_CLIENT_NAME: 'AWAIT_CLIENT_NAME',
    AWAIT_CLIENT_WHATSAPP: 'AWAIT_CLIENT_WHATSAPP',
    AWAIT_CLIENT_EMAIL: 'AWAIT_CLIENT_EMAIL',
    AWAIT_CLIENT_NOTES: 'AWAIT_CLIENT_NOTES',
    AWAIT_PRODUCT_NAME: 'AWAIT_PRODUCT_NAME',
    AWAIT_PRODUCT_DURATION: 'AWAIT_PRODUCT_DURATION',
    AWAIT_PRODUCT_NOTES: 'AWAIT_PRODUCT_NOTES',
    AWAIT_PRODUCT_USERNAME: 'AWAIT_PRODUCT_USERNAME',
    AWAIT_PRODUCT_PASSWORD: 'AWAIT_PRODUCT_PASSWORD',

    // Pasos Flujos Genéricos de Selección
    AWAIT_CLIENT_SELECTION_FOR_PRODUCT: 'AWAIT_CLIENT_SELECTION_FOR_PRODUCT',
    AWAIT_PRODUCT_DETAILS: 'AWAIT_PRODUCT_DETAILS',
    AWAIT_CLIENT_SELECTION_FOR_DELETION: 'AWAIT_CLIENT_SELECTION_FOR_DELETION',
    AWAIT_CLIENT_SELECTION_FOR_RENEWAL: 'AWAIT_CLIENT_SELECTION_FOR_RENEWAL',
    AWAIT_PRODUCT_SELECTION_FOR_RENEWAL: 'AWAIT_PRODUCT_SELECTION_FOR_RENEWAL',
    AWAIT_DURATION_FOR_RENEWAL: 'AWAIT_DURATION_FOR_RENEWAL',

    // Pasos Flujo de Actualización
    AWAIT_CLIENT_SELECTION: 'AWAIT_CLIENT_SELECTION',
    AWAIT_UPDATE_TYPE: 'AWAIT_UPDATE_TYPE',
    AWAIT_PRODUCT_SELECTION: 'AWAIT_PRODUCT_SELECTION',
    AWAIT_FIELD_SELECTION: 'AWAIT_FIELD_SELECTION',
    AWAIT_NEW_VALUE: 'AWAIT_NEW_VALUE',
});

module.exports = {
    ROLES,
    PRODUCT_STATUS,
    FLOW_STEPS
};